export const tecnicasAgrotecnicasDatasets = [
  {
    ORDEN: 12,
    MODALIDAD: 'TÉCNICA',
    ESTABLECIMIENTO: 'EPET N° 1',
    LOCALIDAD: 'FORMOSA',
    TITULOS: "TEC. EN ELECTRONICA;TEC. MAESTRO MAYOR DE OBRAS;TEC. EN EQUIPOS E INSTALACIONES ELECTROMECÁNICAS",
    DOCENTES: 139,
    ADMINISTRATIVO: 13,
    AUTORIDADES: 6,
    SECCIONES: 45,
    MATRICULA: 1228
  },
  {
    ORDEN: 13,
    MODALIDAD: 'TÉCNICA',
    ESTABLECIMIENTO: 'EPET N° 2',
    LOCALIDAD: 'FORMOSA',
    TITULOS: "TEC. MECANICO, TEC. QUIMICO",
    DOCENTES: 109,
    ADMINISTRATIVO: 15,
    AUTORIDADES: 3,
    SECCIONES: 29,
    MATRICULA: 754
  },
  {
    ORDEN: 18,
    MODALIDAD: 'TÉCNICA',
    ESTABLECIMIENTO: 'EPET N° 7',
    LOCALIDAD: 'FORMOSA',
    TITULOS: "TEC. EN AUTOMOTORES, TEC. EN INFORMATICA PROFESIONAL Y PERSONAL, TEC. EN PROGRAMACION",
    DOCENTES: 113,
    ADMINISTRATIVO: 8,
    AUTORIDADES: 8,
    SECCIONES: 37,
    MATRICULA: 1185
  }
];
